### ISSUE TITLE
rikaichamp stops working occasionally

### ISSUE THREAD

**Issue by dafreak29** [birtles/rikaichamp#38] opened 2018-04-11 13:37 UTC
Not sure whether it is a FF issue or the addon,
I am on FFv59.0.2 and rikaichamp just stops working. No popups. Sometimes disabling and re-enabling it fixes the problem for a while then it stops working. Otherwise it requires a browser restart. If I am recalling this correctly, this started to occur on FFv59

edit: I wish I could provide more info but browser console doesnt show anything that is related rikai :/

**Comment by nomakewan** [comment] 2018-04-16 04:51
Am on Firefox Nightly, which is currently FFv61, and Rikaichamp does not work at all. If you attempt to enable it will pulse the 'loading dictionaries' but will never finish loading. Sadly I am not sure what exactly changed under the hood to cause this compatibility issue.

**Comment by birtles** [comment] 2018-04-16 18:08
Wow, yes, today's Nightly completely broke this. It looks like a number of
extensions are broken. In the Browser Console I see:

```
Promise resolved while context is inactive notificationBar.js:124
Promise resolved after context unloaded preload.js:387
Promise resolved after context unloaded rikaicontent.js:1234
```

Only the last is from rikaichamp. Hopefully this is just a regression that
will be fixed in the next 1~2 days.

I'm currently traveling but if this is not fixed by the time I arrive back
in Japan I'll dig into this some more. In the meantime someone else might
be able to dig around for recent regressions that are likely candidates.

That said, I've definitely noticed that rikaichamp is less reliable since
about ~2 months ago. I'm not sure yet what the cause is.

**Comment by birtles** [comment] 2018-04-17 07:24
This latest issue appears to be fixed in the latest Nightly.

(At the same time I appear to be locked out of GitHub somehow :/ )

**Comment by maboroshix** [comment] 2018-05-09 05:43
This is not an 'occasional' issue. This is occurring consistently, where the addon is not working at all unless it is toggled on and off. Incredibly frustrating.

**Comment by birtles** [comment] 2018-05-09 05:48
Yes, it has become a lot more frequently in the last 2~3 months. Something has changed in Firefox but I'm not sure what yet.

**Comment by birtles** [comment] 2018-05-09 07:30
I've started trying to debug this but I'm not really not sure what's going on. If anyone has any clues please follow up here.

For now I've updated a few dependencies. I'll try making TS more strict and see if it catches anything but beyond that I'm a bit stuck for ideas.

**Comment by birtles** [comment] 2018-05-09 07:47
Duplicating this to issue #17 for now.

**Closed by birtles** 2018-05-09 07:47 UTC
