### ISSUE TITLE
Addon stopped working

### ISSUE THREAD

**Issue by mjkarlin** [birtles/rikaichamp#440] opened 2020-11-28 02:31 UTC
Adding this as a new issue because the issue that I added it to has apparently been closed.  If I am duplicating, my apologies.  I'm new to Github and I'm not a programmer

Anyway, I have used rikaichamp for quite a while. As of yesterday (11/26/2020), it stopped working in Firefox. Like other users, I have disabled and re-enabled it and I have tried restarting Firefox and even rebooting. I have tried it with various Japanese language websites as well as Wanikani. No luck. Nothing came up for rikai on Ctrl-Shift-J. I know it's Thanksgiving weekend, so no rush, but any help would be appreciated. One other point, I just realized. I have disabled most pop-ups and tracking in Firefox, but that was several weeks ago and Rikaichamp kept working - it just stopped yesterday and I did not do anything on my end. Firefox is constantly auto-downloading updates, however, and perhaps that has something to do with. A long shot but I thought I should mention it.

**Comment by birtles** [comment] 2020-11-28 11:11
Hi! Thank you so much for taking the time to file this issue. I'm really sorry about the trouble you've faced.

I released an update to Rikaichamp just a few days so that is very likely the reason for the trouble you are facing. I'm not sure why it would stop working, however. Does the icon in the toolbar show up as normal? i.e. turned on and not showing any errors?

One thing that would help if you're feeling adventurous.

1. Type `about:debugging` in the location bar and press Enter.
2. Choose "This Firefox".
3. From the list of extensions, find Firefox and look for the "Internal UUID".

If you can report that internal UUID here I can check if Rikaichamp has posted any error messages to the error reporting service it uses.

(One theory: It might be possible that when you disabled most tracking it turned off the ability for Rikaichamp to store data and the new version is trying to re-download the data and failing. It should still work even when it can't store data but I haven't tested that recently.)

**Comment by mjkarlin** [comment] 2020-11-28 17:09
No need to be sorry.  I’m grateful you replied so soon.

 

So, I went to This Firefox and rikaichamp was not listed on the list of extensions.  That’s odd because if you go to add-ons, Rikaichamp was there and it was enabled.

 

So, next I cleared all my cookies and stored data, changed the tracking to standard, exited Firefox, and restarted.  Now, RIkaichamp shows up in the Extension list.  However, while it has an Extension ID, unlike the other extensions the Manifest URL is blank.  When I clicked on Inspect, I got an error message TypeError: target is null.  Rikaichamp is still not working.

 

You mentioned that you recently did an update.  It’s also true that Firefox often does updates.

 

Finally, does Rikaichamp  work with Chrome?  I don’t think it does.  If so, any recommendations for a Chrome extension?

 

Does this help?

 

Michael

**Comment by birtles** [comment] 2020-11-28 23:58
> So, next I cleared all my cookies and stored data, changed the tracking to standard, exited Firefox, and restarted. Now, RIkaichamp shows up in the Extension list. However, while it has an Extension ID, unlike the other extensions the Manifest URL is blank. When I clicked on Inspect, I got an error message TypeError: target is null. Rikaichamp is still not working.

Thank you so much for trying all this! That's very odd that Rikaichamp has no Manifest URL and produces that error.

Have you tried removing Rikaichamp and re-installing it? You should be able to remove it from the regular add-ons page.

> Finally, does Rikaichamp work with Chrome? I don’t think it does. If so, any recommendations for a Chrome extension?

Unfortunately it doesn't yet. It mostly works but Chrome is missing some functions for working with text boxes so I need to rewrite that part to work with Chrome. I hope to finish that in January. Until then, there is Rikaikun for Chrome. Rikaichamp is based on Rikaikun but has been extended quite a bit.

You can follow issue #352 and issue #86 if you wish to know when Rikaichamp is available for Chrome.

**Comment by mjkarlin** [comment] 2020-11-29 01:28
Thanks again.  See below in red.

**Comment by birtles** [comment] 2020-11-30 09:29
#444 provides more details on what I believe is the same issue. My current best guess is some sort of memory constraint issue, but I really don't know.

One rather drastic thing you could try is to "Refresh Firefox" by going to `about:profiles` and choosing "Refresh Firefox". That fixes some problems but it also deletes all your cookies and settings and add-ons meaning you need to re-install them all and re-login to all your sites. Also, if the root cause is memory, then it might not help after all.

**Comment by birtles** [comment] 2020-11-30 09:30
If this does prove to be a memory issue then hopefully the next major release will alleviate it.

**Comment by birtles** [comment] 2020-12-01 23:20
Hi @mjkarlin, I wonder if you would be able to provide any of the information described here: https://github.com/birtles/rikaichamp/issues/444#issuecomment-736709338

That comment is from the Mozilla engineer who is offering to help debug this. Thank you!

**Comment by birtles** [comment] 2021-01-25 00:31
Closed as per https://github.com/birtles/rikaichamp/issues/444#issuecomment-766469957

**Closed by birtles** 2021-01-25 00:31 UTC
