### ISSUE TITLE
YouTube subtitles: words won't get selected wholly across spans

### ISSUE THREAD

**Issue by Des-Nerger** [birtles/rikaichamp#535] opened 2021-02-23 12:43 UTC
I made simplest possible furigana-containing YouTube subtitles.
When I hover over, let's say, the word `疲れて`, then only `疲` gets selected, `れて` doesn't. So I can't appreciate the rikaichamp deconjugation feature for this kind of words.
But if I go to Firefox Inspector and remove the `<span>` tags around both `<ruby>...</ruby>` and `れて` then the selection starts working properly. Yet if I just replace `<ruby>...</ruby>` with `疲`, it doesn't fix that. So I believe the bug all has to do with spans and not ruby tags.
 ![youtube_furigana](https://user-images.githubusercontent.com/7359990/108843413-5a415d00-7626-11eb-849e-473d5ef5fd3e.png)

**Comment by birtles** [comment] 2021-02-24 00:04
Hi! Thank you for filing this issue!

I had a look into it and I suspect the problem is because you have `display: inline-block` on the spans. Rikaichamp builds up the string to lookup by traversing over inline elements and ruby elements. However, it treats `display: inline-block` as signifying the start of a new chunk of text so it will stop traversing text if it sees a new `inline-block` element.

You can reproduce this with the following minimal test case:

```html
<p><ruby><span>疲</span><rt>つか</rt></ruby><span style="display: inline-block">れた</span></p>
```

Is this HTML something that you are producing or something YouTube is producing?

**Comment by Des-Nerger** [comment] 2021-02-25 14:39
Just to be sure, I have just tried multiple browsers and PCs, and `display: inline-block` is always there. (You can reproduce it yourself if you don't mind retyping the link from the screenshot.)
I think it's just the way YouTube renders SRV3 spans (denoted by `s` tag there).
Here's how relevant sections of my source SRV3 subtitles looked like:
```xml
<?xml version="1.0" encoding="utf-8" ?><timedtext format="3">
<head>
<pen id="1" rb="1" />  <!-- so that <s p="1"> will work like html's <rb> -->
<pen id="2" rb="2" />  <!-- so that <s p="2"> will work like <rp> -->
<pen id="4" rb="4" />  <!-- so that <s p="4"> will work like <rt> -->
<wp id="0" ap="7" ah="50" av="75" />  <!-- in order to raise subtitles higher -->
</head>
<body>
...
<p wp="0" t="153340" d="5689"><s p="1">夜</s><s p="2">(</s><s p="4">よる</s><s p="2">)</s>に　<s p="1">踊</s><s p="2">(</s><s p="4">おど</s><s p="2">)</s>り<s p="1">疲</s><s p="2">(</s><s p="4">つか</s><s p="2">)</s>れて</p>
...
</body>
</timedtext>
```
Nothing fancy. Spans themselves are just minimal ones to make a rubied text happen.
> Rikaichamp treats display: inline-block as signifying the start of a new chunk of text so it will stop traversing text if it sees a new inline-block element

Is it for something important? If so, would it make sense to at least add an option to disable that behavior?

**Comment by birtles** [comment] 2021-02-26 00:10
Thanks! I'm quite happy to change Rikaichamp to traverse `inline-block` elements (the main reason for not doing so is just for performance--the sooner we can find the end of the input string, the less we need to traverse and subsequently lookup). Do you have a link to some YouTube content where I can test this?

**Comment by Des-Nerger** [comment] 2021-02-26 06:09
If a clickable/machine_readable link is absolutely necessary, here's a second example (which is made by some other person): https://youtu.be/f5f5383Pm00

**Comment by birtles** [comment] 2021-02-26 07:37
> If a clickable/machine-readable link is absolutely necessary, here's a second example (which is made by some other person): https://youtu.be/f5f5383Pm00

I'm sorry, I completely overlooked that you wrote in your previous comment that I can reproduce it from the URL in the screenshot! You're right, I've been able to reproduce it using that link. It should be fixed in the next release, hopefully.

**Closed** 2021-02-26 07:37 UTC
