### ISSUE TITLE
Weird bug in a twitter poll

### ISSUE THREAD

**Issue by InstallGentoo11** [birtles/rikaichamp#52] opened 2018-09-03 16:51 UTC
First thanks for making rikaichan workable on the newer firefox versions! And here is the problem:

I couldn't find any other polls to test it on, but it happens here: https://twitter.com/arimorokoshi415/status/1036651905642983426 
![untitled3](https://user-images.githubusercontent.com/6108677/44996787-88dca080-afb2-11e8-852d-486218c4d793.png)
The extension goes under the time stamp. I haven't seen this happen anywhere else.

**Comment by melink14** [comment] 2018-09-03 17:38
This is because the twitter poll is inside an iframe. rikaichamp is also injected into that iframe and can't extend out of it. You could reposition the box, though it might be possible to detect that automatically.

**Comment by birtles** [comment] 2018-09-05 02:50
Yeah, this is a dupe of #13 I'm afraid.

**Closed by birtles** 2018-09-05 02:50 UTC
