### ISSUE TITLE
not working in dark screen reader view in Firefox 75

### ISSUE THREAD

**Issue by cookieo** [birtles/rikaichamp#236] opened 2020-04-19 00:08 UTC
Also does not work in light screen, but dark screen reading with rakaichamp is very much desired.

**Comment by birtles** [comment] 2020-04-20 01:50
Unfortunately Web Extensions can't currently work in reader mode due to [Mozilla bug 1371786](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786).

**Comment by birtles** [comment] 2020-04-20 01:51
Closing for now. Please re-open if I've misunderstood the bug, however.

Once the issue is resolved in Firefox, Rikaichamp should just work in reader mode.

**Closed by birtles** 2020-04-20 01:51 UTC
