### ISSUE TITLE
Default to other dictionaries when longer word can be parsed

### ISSUE THREAD

**Issue by nicolasmaia** [birtles/rikaichamp#256] opened 2020-04-28 23:41 UTC
For instance, when looking at 井の頭公園, rikai will only look at 井. But it would be more useful if it could detect a longer word and default to other dictionaries, like jmnedict.

**Comment by birtles** [comment] 2020-04-29 03:02
Oh yes, I've wanted that before. If we find a longer match in the names dictionary, we could show that at the top of the list.

**Comment by nicolasmaia** [comment] 2020-07-28 05:31
Ideally other dictionaries too, but I imagine that would have to wait until #41 is done.

I'm very excited with the prospect of perhaps using Wikidata as a names dictionary. Much more complete than JMnedict.

**Comment by birtles** [comment] 2020-09-08 02:31
This should be fixed in the upcoming 0.2.0 release.

<img width="387" alt="name-preview" src="https://user-images.githubusercontent.com/1232595/92427210-dce47600-f1c6-11ea-9b0f-406824e92fa2.png">

It could still use a bit of work, however. For example, you can't highlight the name entry for copying to the clipboard.

**Closed by birtles** 2020-09-08 02:31 UTC

**Comment by nicolasmaia** [comment] 2021-07-25 23:52
Any ideas as to why ブラガ doesn't show the name Braga first?

**Comment by nicolasmaia** [comment] 2021-07-26 00:15
Same issue with キンドル. It sounds like this might be a regression.

**Comment by birtles** [comment] 2021-07-26 00:16
Yes, highly likely to be a regression since I had to rewrite that code to move it from the background page to the content script in order to support the tab feature. I'll look into it this afternoon. Thanks for reporting!

**Comment by birtles** [comment] 2021-07-26 04:41
Actually I'm not sure if this is a regression after all. The reason those two words don't show previews is because the heuristic for showing a preview is that the match has some kanji characters. See the removed code here:

https://github.com/birchill/10ten-ja-reader/commit/b7f4233edebd33ac56abcf70c853063723fc09ea#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291fL518-L541

That said, I'm not sure if the old code actually worked as expected (the condition it uses seems a bit odd). Furthermore the comment with the old code suggests we intended to show matches with _katakana_ but not _hiragana_-only matches.

In https://github.com/birchill/10ten-ja-reader/commit/a3a60a807b1e83b991c99c22808005d4b20ef13e I've made it show katakana matches to now so those two example should show the preview correctly in the next release.
