### ISSUE TITLE
Popup is obscured in certain situations

### ISSUE THREAD

**Issue by Kala-J** [birtles/rikaichamp#188] opened 2020-01-30 06:30 UTC
When viewing some product descriptions on amazon.co.jp the popup is obscured. It is likely that other websites using similar styling are also affected.

For example, looking at the current best-selling light novel:

<img width="486" alt="rb7" src="https://user-images.githubusercontent.com/47021172/73425330-a7e08d00-4374-11ea-8ab5-f04cad699619.png">

Even if you expand the "read more" section, it still is obscured at the bottom.

Additionally, the 商品の説明 section farther down the page exhibits the same behavior.

**Comment by birtles** [comment] 2020-01-30 06:34
Yeah, I noticed this recently too. I think Amazon changed their layout and are now putting this content in its own `<iframe>`. I think this is basically a dupe of #13.

**Closed** 2020-01-30 06:39 UTC
