### ISSUE TITLE
Please add support for larest thunderbird

### ISSUE THREAD

**Issue by vimesh-pro** [birtles/rikaichamp#131] opened 2019-10-29 01:52 UTC
Please add support for larest thunderbird

**Comment by birtles** [comment] 2019-10-29 01:54
Unfortunately it's not currently possible since Thunderbird does not have the required APIs for running JS on message view or compose view although I have interacting with Thunderbird devs to try to get them added.

Closing as a dupe of #46.

**Closed by birtles** 2019-10-29 01:54 UTC

**Comment by vimesh-pro** [comment] 2019-10-31 07:42
What about TB 68.0?
Is there anything changed?

**Comment by birtles** [comment] 2019-10-31 07:43
No, it's still not possible even in the latest development versions I'm afraid.
